[tool.poetry]
name = "server"
version = "0.1.0"
description = "The backend server for the ineview services"
authors = []
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.2"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
