# Generated by Django 4.0.2 on 2022-02-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="descriptions",
            field=models.TextField(
                blank=True,
                help_text="An optional description of the question",
                null=True,
            ),
        ),
    ]
