# Generated by Django 4.0.2 on 2022-02-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_descriptions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="descriptions",
            new_name="description",
        ),
    ]
