# Generated by Django 3.2 on 2022-02-19 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20220219_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time this question set was created on'),
            preserve_default=False,
        ),
    ]
