from django.conf import settings
from django.db import models as django_models
from questions import models as question_models


class AttemptSet(django_models.Model):
    user = django_models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=django_models.CASCADE,
        help_text="The user who attempted this question set",
    )
    attempted_at = django_models.DateTimeField(auto_now_add=True)
    is_processed = django_models.BooleanField(
        default=False,
        help_text="Whether this entire attempt has been processed yet",
    )

    def __str__(self):
        return f"Attempt set ID: {self.id}"

    @property
    def is_processed(self):
        """Whether all the attempts in this set have been processed"""
        return (
            False
            if self.attempt_set.count() == 0
            else all(map(lambda a: a.is_processed, self.attempt_set.all()))
        )

    @property
    def is_purged(self):
        """Whether all the attempts in this set have been purged"""
        return (
            False
            if self.attempt_set.count() == 0
            else all(map(lambda a: a.is_purged, self.attempt_set.all()))
        )


class Attempt(django_models.Model):
    is_processed = django_models.BooleanField(
        default=False,
        help_text="Whether this video file has been processed yet",
    )
    video_file = django_models.FileField(upload_to="videos/")
    question = django_models.ForeignKey(
        question_models.Question,
        on_delete=django_models.CASCADE,
        help_text="The question to which this attempt belongs",
    )
    data = django_models.JSONField(
        help_text="The data that was generated by the facial recognition algorithm",
        blank=True,
        null=True,
    )
    attempt_set = django_models.ForeignKey(
        AttemptSet,
        on_delete=django_models.CASCADE,
        help_text="The attempt set to which this attempt belongs",
    )
    # For space considerations, attempts that have been processed are deleted automatically
    is_purged = django_models.BooleanField(
        default=False,
        help_text="Whether the associated video file has been deleted from disc",
    )

    def __str__(self):
        return f"Attempt ID: {self.id}"
