# Generated by Django 4.0.2 on 2022-02-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoupload",
            name="is_processed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this video file has been processed yet",
            ),
        ),
    ]
