# Generated by Django 3.2 on 2022-02-23 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questions", "0005_questionset_created_date"),
        ("video", "0002_videoupload_is_processed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this video file has been processed yet",
                    ),
                ),
                ("video_file", models.FileField(upload_to="videos/")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="The data that was generated by the facial recognition algorithm",
                        null=True,
                    ),
                ),
                (
                    "is_purged",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the associated video file has been deleted from disc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttemptSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who attempted this question set",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="VideoUpload",
        ),
        migrations.AddField(
            model_name="attempt",
            name="attempt_set",
            field=models.ForeignKey(
                help_text="The attempt set to which this attempt belongs",
                on_delete=django.db.models.deletion.CASCADE,
                to="video.attemptset",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="question",
            field=models.ForeignKey(
                help_text="The question to which this attempt belongs",
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.question",
            ),
        ),
    ]
